Updated to LESS 2.7.1
jgonera/autoless pull request #27
Opened 2016-12-22 13:10 UTC by johanberonius

Quick fix to make it work with LESS `2.7.1`.

2016-12-23 17:06 UTC, jgonera requested changes
Thanks for the patch! A few minor comments inline.

2016-12-23 17:06 UTC, jgonera commented on lib/lessfile.js
> +    less.render(fs.readFileSync(this.file, 'utf-8'), {
Let's put each argument to this method in a new line for clarity.

2016-12-23 17:06 UTC, jgonera commented on lib/lessfile.js
> +      self.imports = output.imports;
Indentation.

2016-12-23 17:06 UTC, jgonera commented on lib/lessfile.js
> +    compileOptions.paths = path.dirname(this.file);
Can we DRY this (L24-25)?

2016-12-29 16:24 UTC, johanberonius reviewed
Parse and render methods now updated to use the same options, just like`less.Parser` used before.

2018-07-05 15:18 UTC, nutgaard commented
@jgonera Anything missing from getting this merged and published?

2021-05-05 01:52 UTC, jgonera commented
Sorry, I'm not going to maintain this project anymore since modern web development uses Webpack/Rollup for everything. I'm closing this PR before archiving the repo, feel free to fork it if you really need autoless.

2021-05-05 01:52 UTC, closed without merging

2021-05-05 01:53 UTC, jgonera commented
Sorry for not merging/reviewing again back in the day.